spring:
   application:
       name: CONFIG-DEFAULT

eureka:
  instance:
    hostname: localhost
    ip-address: true
    
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone : http://localhost:8761/eureka
